//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbsoluteAPI.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class APP_LS_COMPETIZIONI_EVENTI_V
    {
        public int ID { get; set; }
        public string NOME { get; set; }
        public int ANNO { get; set; }
        public int ID_EVENTI { get; set; }
        public string NOME_EVENTI { get; set; }
        public string TIPO_GIRONE { get; set; }
    }
}
