//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbsoluteAPI.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class APP_BANNER_V
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> DATA_INS { get; set; }
        public string LOGIN_INS { get; set; }
        public Nullable<System.DateTime> DATA_AGG { get; set; }
        public string LOGIN_AGG { get; set; }
        public string TITOLO { get; set; }
        public string IMMAGINE { get; set; }
        public string IMMAGINE_PREV { get; set; }
        public string LINK_ESTERNO { get; set; }
        public Nullable<int> ABILITATO { get; set; }
    }
}
