//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbsoluteAPI.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLASSIFICHE_SQUADRE_V
    {
        public string NOME { get; set; }
        public int ID { get; set; }
        public Nullable<System.DateTime> DATA_INS { get; set; }
        public string LOGIN_INS { get; set; }
        public Nullable<System.DateTime> DATA_AGG { get; set; }
        public string LOGIN_AGG { get; set; }
        public int ID_EVENTO { get; set; }
        public int ID_SQUADRA { get; set; }
        public int PUNTI { get; set; }
        public int GIOCATE { get; set; }
        public int VINTE { get; set; }
        public int PAREGGIATE { get; set; }
        public int PERSE { get; set; }
        public int GF { get; set; }
        public int GS { get; set; }
        public int AZZERATA { get; set; }
        public int ORDINE { get; set; }
        public int punti_penalita { get; set; }
        public Nullable<int> PUNTI_RANKING_MANUALI { get; set; }
    }
}
