//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbsoluteAPI.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EVENTI
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> DATA_INS { get; set; }
        public string LOGIN_INS { get; set; }
        public Nullable<System.DateTime> DATA_AGG { get; set; }
        public string LOGIN_AGG { get; set; }
        public int ID_COMPETIZIONE { get; set; }
        public string NOME { get; set; }
        public int ANNO { get; set; }
        public string COPERTINA { get; set; }
        public string TIPO_GIRONE { get; set; }
        public string ORDINE_CLASSIFICA { get; set; }
        public int STATO { get; set; }
        public string URL_TABELLONE_FASIFINALI { get; set; }
        public string IMG_COPERTINA { get; set; }
        public Nullable<int> ORDINE { get; set; }
        public string BOX_COLOR { get; set; }
    }
}
