//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbsoluteAPI.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class INCONTRI_RISULTATI_V
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> DATA_INS { get; set; }
        public string LOGIN_INS { get; set; }
        public Nullable<System.DateTime> DATA_AGG { get; set; }
        public string LOGIN_AGG { get; set; }
        public Nullable<System.DateTime> DATA_EVENTO { get; set; }
        public string ORA { get; set; }
        public Nullable<System.DateTime> DATA_POSTICIPO { get; set; }
        public int ID_CALENDARIO { get; set; }
        public string NOTE { get; set; }
        public int ID_SQUADRA_1 { get; set; }
        public int ID_SQUADRA_2 { get; set; }
        public int ID_CAMPO { get; set; }
        public int STATO { get; set; }
        public string NOTE_AMMINISTRATORI { get; set; }
        public string ORA_POSTICIPO { get; set; }
        public Nullable<int> ID_ARBITRO { get; set; }
        public Nullable<int> TOSTA { get; set; }
        public Nullable<int> CONFERMA_ARBITRO { get; set; }
        public Nullable<int> CONFERMA_STATISTICHE { get; set; }
        public string NOTE_REFERTO_SITO { get; set; }
        public Nullable<int> ID_CAMPO_RECUPERO { get; set; }
        public string TESTO_SEGNALAZIONE_ARBITRI { get; set; }
        public bool ESCLUDI_DESIGNATORE { get; set; }
        public Nullable<int> OFC_CalendarioGiornate_ID { get; set; }
        public Nullable<int> PUNTEGGIO_1 { get; set; }
        public Nullable<int> PUNTEGGIO_2 { get; set; }
        public string SCHEDINA { get; set; }
        public int STATO_RISULTATO { get; set; }
    }
}
