//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbsoluteAPI.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LS_INCONTRI
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> DATA_INS { get; set; }
        public string LOGIN_INS { get; set; }
        public Nullable<System.DateTime> DATA_AGG { get; set; }
        public string LOGIN_AGG { get; set; }
        public int ID_INCONTRO { get; set; }
        public Nullable<int> PUNTEGGIO_1 { get; set; }
        public Nullable<int> PUNTEGGIO_2 { get; set; }
        public int FL_LIVE { get; set; }
        public int ABILITATO { get; set; }
    }
}
