SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO


ALTER VIEW APP_ELENCO_SQUADRE_V AS
	SELECT 
		DISTINCT(EVENTI_SQUADRE.ID_SQUADRA),	
		SQUADRE.NOME,
		SQUADRE.LOGO
	FROM 
		EVENTI_SQUADRE
	JOIN 
		SQUADRE
ON 
	EVENTI_SQUADRE.ID_SQUADRA = SQUADRE.ID
	WHERE EVENTI_SQUADRE.STATO = 1
	AND EVENTI_SQUADRE.ID_EVENTO IN (SELECT ID_EVENTI FROM APP_LS_COMPETIZIONI_EVENTI_V)
	--ORDER BY NOME ASC